name: CI/CD hdev_client to AWS S3

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA264FV5MWPNFTR67R
          aws-secret-access-key: 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
          aws-region: ap-northeast-2

      - name: 리액트 빌드
        run: |
          npm install
          npm run build

      - name: 빌드한 파일 S3에 업로드
        run: aws s3 sync build/ s3://itstudyreact --acl public-read
        env:
          AWS_ACCESS_KEY_ID: AKIA264FV5MWPNFTR67R
          AWS_SECRET_ACCESS_KEY: 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
